# Dockerfile.dev
FROM node:18-alpine

WORKDIR /usr/src/app

# Instalar dependencias necesarias para desarrollo
RUN apk add --no-cache bash openssl

# Copiar archivos de dependencias
COPY package*.json ./

# Instalar TODAS las dependencias (incluye las de desarrollo)
RUN npm install

CMD ["ls"]

# Copiar el esquema Prisma y el resto del código
COPY prisma ./prisma
COPY tsconfig.json ./
#COPY nest-cli.json ./        # 👈 si usas Nest CLI, también este
#COPY .env ./                 # 👈 opcional, si lo usas en desarrollo
COPY src ./src
COPY . .

# Generar cliente Prisma (ahora sí encuentra el schema)
RUN npx prisma generate

# Exponer puerto del servidor NestJS
EXPOSE 3000

# Comando por defecto (modo watch)
CMD ["npm", "run", "start:dev"]
