# Dockerfile.dev
FROM node:18-alpine

WORKDIR /usr/src/app

# Instalar dependencias necesarias para desarrollo
RUN apk add --no-cache bash openssl

# Copiar archivos de dependencias
COPY package*.json ./

# Instalar TODAS las dependencias (incluye las de desarrollo)
RUN npm install

# Copiar todo el código fuente
COPY . .

# Generar cliente Prisma
RUN npx prisma generate

# Exponer puerto del servidor NestJS
EXPOSE 3000

# Comando por defecto (modo watch)
CMD ["npm", "run", "start:dev"]
